<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LcdDriver.TrofeoVisionLy\LcdDriver.TrofeoVisionLy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.153.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Example\libusb-1.0.dll" Link="libusb-1.0.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
